### ISSUE TITLE
Create homepage-template for base.html

### ISSUE THREAD

**Issue by bocian67** [Dezentrale-eV/dezentrale_web#16]

**Comment by elbenfreund** [comment]
What exactly should be done so the issue can be "closed"?

**Comment by bocian67** [comment]
- Creating a very first draft of the landing page

- while beeing in progress, new issues will appear -> this one like a headline or goal

**Comment by elbenfreund** [comment]
Issues should always be actionable and relate to a particular verifyable task to be done. Unfortunately github does not have something like JIRAs "epics". What you can to for "meta issues" is use githubts markdown (``- [ ]``) to create a list of "sub-task" issues.

For example:

```
- [ ] Create basic layout and design in ``base.html``.
- [ ] Create template for landing page.
...
```

Each list item can then link to a seperate issue.

**Comment by bocian67** [comment]
@Lokke can you please make a feature branch and push what you work on?

**Comment by elbenfreund** [comment]
any news on this @Lokke ?

**Comment by Rascat** [comment]
I would close this issue, because i think the task at hand changed quite a bit.
Since @Lokke provided us with an discrete template, we need to do two things (in my opinion):

- discuss which parts of the homepage are going to be static, and which will be represented by the homepage model
- integrate our wagtail homepage model in the template

Do you agree that it is reasonable to work on these issues @bocian67 @elbenfreund ??
If yes, i would create two new issues (one for discussion and one for the actual implementation) and close this one.

**Comment by bocian67** [comment]
I agree on closing this one, since we should keep Issues as short as possible, but I disagree on discussing - the actual template is very clear about header - content - footer, and I don't think that we could mess up with that.

**Comment by elbenfreund** [comment]
I think @Rascat seperation of questions is absolutly correct

>- discuss which parts of the homepage are going to be static, and which will be represented by the >homepage model
>- integrate our wagtail homepage model in the template

Wether you need/want to discuss the content of the landing page or not is up to you. But its a different issue than using Lokkes design as base template.
