### ISSUE TITLE
Re-evaluate the use of ``StreamField`` for 'blog.BlogPage.content

### ISSUE THREAD

**Issue by elbenfreund** [Dezentrale-eV/dezentrale_web#67]
I suspect you are a bit frustrated with me bringing this up again, but I as it is *right now* I think the ``blog.models.BlogPage.content`` is absolutely broken. And I fail too see any reasonable defence for its current state.

Streamfields are orderable. I can not, for the live of me, concieve a sane context in which that makes sense for headings relative to actual content. But if the streamfield contains only "content"  blocks, I fail to see the added value over just using a (Rich)TextField.

This issue suggests:
- move ``headline`` out of the streamfield
- turn the streamfield into a regular (Rich)TextField

**Comment by bocian67** [comment]
Since we clarified that the Heading-Block doesn't mean a 'real' heading, but an subheading, the streamfield is a good choice - but our time runs out so we should now focus on the landingpage. 
IMHO we shouldn't include the blogs right now, instead make them great and publish them afterwards, and now downgrade them to a Textfield.

**Comment by bocian67** [comment]
I think this is now clear and in #50 solved. I will close this.
